# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TocmQNA9hkhgvDRtG0IDltUQLNsTv6oD
"""

import numpy as np
import matplotlib.pyplot as plt

# Yurak urishi signalini yaratish
def generate_heartbeat(t):
    """Yurak urish apparati signali."""
    signal = (
        1.2 * np.exp(-((t - 0.2) / 0.1)**2)  # P-to'lqin
        - 5 * np.exp(-((t - 0.4) / 0.03)**2)  # Q-to'lqin
        + 30 * np.exp(-((t - 0.6) / 0.05)**2)  # R-to'lqin
        - 7 * np.exp(-((t - 0.8) / 0.03)**2)  # S-to'lqin
        + 0.5 * np.exp(-((t - 1.2) / 0.1)**2)  # T-to'lqin
    )
    return signal

# Vaqt oralig'i
t = np.linspace(0, 2, 1000)  # 2 soniyalik signal

# Yurak urishini chizish
heartbeat_signal = generate_heartbeat(t)

# Grafikka bir necha urishlar qo'shish
repeated_signal = np.tile(heartbeat_signal, 3)  # Signalni 3 marta takrorlash
t_repeated = np.linspace(0, 6, len(repeated_signal))

# Grafikni chizish
plt.figure(figsize=(10, 4))
plt.plot(t_repeated, repeated_signal, color='red', linewidth=2)
plt.title("Yurak Urish Apparati Signali (EKG)")
plt.xlabel("Vaqt (soniya)")
plt.ylabel("Signal kuchi (mV)")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.array([5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5])

plt.pie(x)
plt.show()